config:
  target: 'http://localhost:3000' # Express server endpoint
  phases:
    - duration: 10 # Test duration in seconds
      arrivalRate: 1 # New virtual users per second
      name: "Sanity"
    - duration: 10 # Test duration in seconds
      arrivalRate: 1 # New virtual users per second
      name: "Warm up"
    - duration: 10 # Test duration in seconds
      arrivalRate: 1 # New virtual users per second
      name: "Load Tests"

scenarios:
  - flow:
      - get:
          url: "/create"
      - think: 20
      - get:
          url: "/harvest"
      - think: 20
      - get:
          url: "/cleanup"
